/*
 * device_conf.h
 *
 *  Created on: 2018/07/03
 *      Author: Keshikan
 */

#ifndef DEVICE_CONF_H_
#define DEVICE_CONF_H_


#define LED_IN1_GPIO GPIOE
#define LED_IN1_PIN GPIO_PIN_10

#define LED_IN2_GPIO GPIOE
#define LED_IN2_PIN GPIO_PIN_11

#define LED_IN3_GPIO GPIOE
#define LED_IN3_PIN GPIO_PIN_12

#define LED_IN4_GPIO GPIOE
#define LED_IN4_PIN GPIO_PIN_13

#define LED_IN5_GPIO GPIOE
#define LED_IN5_PIN GPIO_PIN_14

#define LED_IN6_GPIO GPIOE
#define LED_IN6_PIN GPIO_PIN_15

#define LED_IN7_GPIO GPIOB
#define LED_IN7_PIN GPIO_PIN_10

#define LED_IN8_GPIO GPIOB
#define LED_IN8_PIN GPIO_PIN_11

#define LED_OUT1_GPIO GPIOB
#define LED_OUT1_PIN GPIO_PIN_12

#define LED_OUT2_GPIO GPIOB
#define LED_OUT2_PIN GPIO_PIN_13

#define LED_OUT3_GPIO GPIOB
#define LED_OUT3_PIN GPIO_PIN_14

#define LED_OUT4_GPIO GPIOB
#define LED_OUT4_PIN GPIO_PIN_15

#define LED_OUT5_GPIO GPIOD
#define LED_OUT5_PIN GPIO_PIN_8

#define LED_OUT6_GPIO GPIOD
#define LED_OUT6_PIN GPIO_PIN_9

#define LED_OUT7_GPIO GPIOD
#define LED_OUT7_PIN GPIO_PIN_10

#define LED_OUT8_GPIO GPIOD
#define LED_OUT8_PIN GPIO_PIN_11

#define LED_POW_GPIO GPIOE
#define LED_POW_PIN GPIO_PIN_9


//UART handler to MIDI PORT
#define MIDI_UART_HANDLER_1 huart3
#define MIDI_UART_HANDLER_2 huart5
#define MIDI_UART_HANDLER_3 huart2
#define MIDI_UART_HANDLER_4 huart1
#define MIDI_UART_HANDLER_5 huart8
#define MIDI_UART_HANDLER_6 huart4
#define MIDI_UART_HANDLER_7 huart7
#define MIDI_UART_HANDLER_8 huart6

#define UART_INSTANCE_PORT1 USART3
#define UART_INSTANCE_PORT2 UART5
#define UART_INSTANCE_PORT3 USART2
#define UART_INSTANCE_PORT4 USART1
#define UART_INSTANCE_PORT5 UART8
#define UART_INSTANCE_PORT6 UART4
#define UART_INSTANCE_PORT7 UART7
#define UART_INSTANCE_PORT8 USART6


#endif /* DEVICE_CONF_H_ */
